server:
  error:
    whitelabel:
      enabled: false
  port: 8088

spring:
  security:
    user:
      name : test
      password : test1234
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: PRODUCT-SERVICE
  cloud:
    config:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/